\set ON_ERROR_STOP on
BEGIN;
CREATE SCHEMA clinical;
CREATE SCHEMA ingest;
CREATE SCHEMA audit;
CREATE DOMAIN clinical.confidence AS numeric(5,4)
  CHECK (VALUE >= 0 AND VALUE <= 1);

CREATE TABLE ingest.file (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blob_uri text NOT NULL,
  blob_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(blob_uri, blob_version)
);
CREATE TABLE ingest.parse_run (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id bigint NOT NULL REFERENCES ingest.file(id),
  idempotency_key text NOT NULL UNIQUE,
  model_version text NOT NULL,
  raw_output_uri text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(id, file_id)
);
CREATE INDEX ON ingest.parse_run(file_id);
CREATE TABLE clinical.document (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id bigint NOT NULL REFERENCES ingest.file(id),
  parse_run_id bigint,
  source_document_key text NOT NULL,
  member_id text, member_id_conf clinical.confidence,
  member_first_name text, member_first_name_conf clinical.confidence,
  member_last_name text, member_last_name_conf clinical.confidence,
  provider_name text, provider_name_conf clinical.confidence,
  provider_npi text, provider_npi_conf clinical.confidence,
  version bigint NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(parse_run_id,file_id) REFERENCES ingest.parse_run(id,file_id),
  UNIQUE(file_id,source_document_key)
);
CREATE TABLE clinical.medication (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint NOT NULL REFERENCES clinical.document(id),
  source_item_key text NOT NULL,
  medication_name text, medication_name_conf clinical.confidence,
  dose text, dose_conf clinical.confidence,
  version bigint NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(document_id,source_item_key)
);
CREATE TABLE clinical.diagnosis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint NOT NULL REFERENCES clinical.document(id),
  source_item_key text NOT NULL,
  diagnosis_code text, diagnosis_code_conf clinical.confidence,
  code_system text, code_system_conf clinical.confidence,
  version bigint NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(document_id,source_item_key)
);
CREATE TABLE clinical.encounter (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint NOT NULL REFERENCES clinical.document(id),
  source_item_key text NOT NULL,
  encounter_date date, encounter_date_conf clinical.confidence,
  encounter_type text, encounter_type_conf clinical.confidence,
  version bigint NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(document_id,source_item_key)
);
CREATE TABLE audit.edit (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_table text NOT NULL, entity_id bigint NOT NULL,
  actor text NOT NULL, edited_at timestamptz NOT NULL DEFAULT now(),
  before_row jsonb NOT NULL, after_row jsonb NOT NULL
);
-- Trusted backend sets app.actor for human edits; never trust this setting as authentication.
-- The pipeline leaves it unset. Changed fields only receive confidence=1.
CREATE FUNCTION clinical.track_edit() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE actor text := nullif(current_setting('app.actor',true),'');
        payload jsonb := to_jsonb(NEW); old_payload jsonb := to_jsonb(OLD);
        field text;
BEGIN
  IF actor IS NOT NULL THEN
    FOR field IN SELECT jsonb_object_keys(payload) LOOP
      IF payload ? (field || '_conf') AND payload->field IS DISTINCT FROM old_payload->field THEN
        payload := jsonb_set(payload, ARRAY[field || '_conf'], '1.0000'::jsonb);
      END IF;
    END LOOP;
    NEW := jsonb_populate_record(NEW,payload);
  END IF;
  NEW.version := OLD.version + 1;
  NEW.updated_at := clock_timestamp();
  IF actor IS NOT NULL THEN
    INSERT INTO audit.edit(entity_table,entity_id,actor,before_row,after_row)
    VALUES(TG_TABLE_NAME,NEW.id,actor,old_payload,to_jsonb(NEW));
  END IF;
  RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['document','medication','diagnosis','encounter'] LOOP
    EXECUTE format('CREATE TRIGGER track_edit BEFORE UPDATE ON clinical.%I FOR EACH ROW EXECUTE FUNCTION clinical.track_edit()',t);
  END LOOP;
END $$;
COMMIT;
